# Generated by Django 5.0 on 2023-12-06 20:36

import uuid

import django.db.models.deletion
from django.db import migrations, models

import music_tracker.tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                (
                    "year",
                    music_tracker.tracker.models.YearField(
                        max_length=4,
                        validators=[music_tracker.tracker.models.is_valid_year],
                    ),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("listened", models.BooleanField(default=False)),
                ("priority", models.BooleanField(default=False)),
                (
                    "original_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3)],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "re_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3)],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "rank",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="tracker.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopTenAlbumsList",
            fields=[
                (
                    "list_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tracker.list",
                    ),
                ),
                (
                    "year",
                    music_tracker.tracker.models.YearField(
                        max_length=4,
                        unique=True,
                        validators=[music_tracker.tracker.models.is_valid_year],
                    ),
                ),
            ],
            bases=("tracker.list",),
        ),
    ]
