# Generated by Django 5.0 on 2023-12-08 22:11

import django.db.models.deletion
from django.db import migrations, models

import music_tracker.tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_album_id_alter_artist_id_alter_list_id_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObsessionList",
            fields=[
                (
                    "list_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tracker.list",
                    ),
                ),
                (
                    "year",
                    music_tracker.tracker.models.YearField(
                        max_length=4,
                        unique=True,
                        validators=[music_tracker.tracker.models.is_valid_year],
                    ),
                ),
            ],
            bases=("tracker.list",),
        ),
        migrations.CreateModel(
            name="ObsessionSongs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.IntegerField()),
                (
                    "obsession_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.obsessionlist",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.song"
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("ordering", "obsession_list"),
                    ("song", "obsession_list"),
                },
            },
        ),
    ]
