# Generated by Django 5.0 on 2023-12-21 21:21

import django.db.models.deletion
from django.db import migrations, models

import music_tracker.tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_album_unique_together_album_artists_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpotifyTop100List",
            fields=[
                (
                    "list_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="tracker.list",
                    ),
                ),
                (
                    "year",
                    music_tracker.tracker.models.YearField(
                        max_length=4,
                        unique=True,
                        validators=[music_tracker.tracker.models.is_valid_year],
                    ),
                ),
            ],
            bases=("tracker.list",),
        ),
        migrations.CreateModel(
            name="SpotifyTop100Songs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordering", models.IntegerField()),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.song"
                    ),
                ),
                (
                    "top_100_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.spotifytop100list",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("ordering", "top_100_list"),
                    ("song", "top_100_list"),
                },
            },
        ),
    ]
