# Generated by Django 5.2.7 on 2025-10-29 16:53

import uuid

import django.db.models.deletion
from django.db import migrations, models

import music_tracker.tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_spotifytop100list_spotifytop100songs"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistAlbumRanking",
            fields=[
                (
                    "id",
                    music_tracker.tracker.models.UUIDPKField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.artist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArtistAlbumRankingEntry",
            fields=[
                (
                    "id",
                    music_tracker.tracker.models.UUIDPKField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rank", models.IntegerField()),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this album's ranking",
                        null=True,
                    ),
                ),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracker.album"
                    ),
                ),
                (
                    "ranking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracker.artistalbumranking",
                    ),
                ),
            ],
            options={
                "unique_together": {("ranking", "album"), ("ranking", "rank")},
            },
        ),
    ]
